# Change these first
owner: rajkumaar23 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Online Home of Rajkumar
    url: https://rajkumaar.co.in
  - name: Playstore API
    url: https://api-playstore.rajkumaar.co.in
    maxResponseTime: 120000
  - name: Plausible Analytics
    url: https://plausible.pi.rajkumaar.co.in
  - name: vCard Editor
    url: https://vcard-editor.rajkumaar.co.in    

status-website:
  cname: status.rajkumaar.co.in
  name: Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page for my online services.
  scripts:
    - src: https://plausible.pi.rajkumaar.co.in/js/script.js
      defer: true
      dataDomain: status.rajkumaar.co.in
  navbar:
    - title: Home
      href: https://rajkumaar.co.in
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
