# Change these first
owner: rajkumaar23 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Homelab
    url: $HOMELAB_SITE

status-website:
  cname: status.rajkumaar.co.in
  name: Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  js: "var script = document.createElement('script'); script.src = 'https://gc.zgo.at/count.js'; script.defer = true; script.dataset['goatcounter'] = 'https://status-rajkumaar.goatcounter.com/count'; document.head.appendChild(script);"
  introMessage: This is a status page for my online services.
  navbar:
    - title: Home
      href: https://rajkumaar.co.in
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
