# Change these first
owner: rajkumaar23 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Online Home of Rajkumar
    url: https://rajkumaar.co.in
  - name: Playstore API
    url: https://api-playstore.rajkumaar.co.in
  - name: Plausible Analytics
    url: https://plausible.pi.rajkumaar.co.in    

status-website:
  cname: status.rajkumaar.co.in
  name: Uptime
  logoUrl: https://avatars.githubusercontent.com/u/37476886?s=460&u=99db89835ee1162724b904e0260e94522cb91470&v=4
  navbar:
    - title: Home
      href: https://rajkumaar.co.in
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
