# Change these first
owner: rajkumaar23 # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Online Home of Rajkumar
    url: https://rajkumaar.co.in
  - name: Playstore API
    url: https://api-playstore.rajkumaar.co.in/json?id=in.co.rajkumaar.amritarepo
    icon: https://www.gstatic.com/android/market_images/web/favicon_v3.ico
  - name: vCard Editor
    url: https://vcard-editor.rajkumaar.co.in    
  - name: Pi - Home Page
    url: https://pi.rajkumaar.co.in
    icon: https://pi.rajkumaar.co.in/favicon.ico
  - name: Piped - YT Frontend
    url: https://yt.rajkumaar.co.in
    icon: https://yt.rajkumaar.co.in/favicon.ico
  - name: Piped API
    url: https://api.yt.rajkumaar.co.in/healthcheck
    icon: https://yt.rajkumaar.co.in/favicon.ico
  - name: Dozzle
    url: https://dozzle.rajkumaar.co.in/healthcheck
    icon: https://dozzle.dev/favicon.ico
  - name: Jellyfin
    url: https://jellyfin.rajkumaar.co.in
    icon: https://jellyfin.org/images/favicon.ico
  - name: CodeChef Contest Arena - API
    url: https://api.codechef-arena.rajkumaar.co.in/healthcheck
    icon: https://codechef.com/favicon.ico
  - name: Amrita Repository - Telegram Bot
    url: https://amrita-repo-bot.rajkumaar.co.in/healthcheck
    icon: https://raw.githubusercontent.com/rajkumaar23/AmritaRepo/master/app/src/main/res/drawable/logosq.png

status-website:
  cname: status.rajkumaar.co.in
  name: Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  js: "var script = document.createElement('script'); script.src = 'https://gc.zgo.at/count.js'; script.defer = true; script.dataset['goatcounter'] = 'https://status-rajkumaar.goatcounter.com/count'; document.head.appendChild(script);"
  introMessage: This is a status page for my online services.
  navbar:
    - title: Home
      href: https://rajkumaar.co.in
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
